### ISSUE TITLE
Conflict with Shaders when I press F5.

### ISSUE THREAD

**Issue by Mihail001** [przemykomo/simple-planes#61] opened 2021-03-27 19:44 UTC
I have a conflict with any shaders if I am flying on the helicopter or large plane. When I press F5 everything is getting darker!
In the first screenshots without pressing F5 on the helicopter and large plane
![2021-03-27_22 30 38](https://user-images.githubusercontent.com/74407310/112732713-a563ce00-8f4c-11eb-90d3-8755d05fae4f.png)
![2021-03-27_22 32 17](https://user-images.githubusercontent.com/74407310/112732718-ad237280-8f4c-11eb-8d14-0c1057364bee.png)
But in the second screenshots with pressed F5 on the helicopter and large plane
Everything is getting darker!
![2021-03-27_22 30 50](https://user-images.githubusercontent.com/74407310/112732745-d80dc680-8f4c-11eb-8841-fa186134f638.png)
![2021-03-27_22 33 11](https://user-images.githubusercontent.com/74407310/112732748-da702080-8f4c-11eb-8924-9781afeec25b.png)
And on the plane (not large) I haven't got this problem.
I use:
Simpleplanes-1.16.4-4.1.2
Forge: 1.16.5-forge-36.1.2
OptiFine_1.16.5_HD_U_G7
And some other mods that may not apply to this issue.

**Comment by przemykomo** [comment] 2021-03-27 19:46
Works as intended. I won't fix optifine bugs.

**Closed by przemykomo** 2021-03-27 19:46 UTC
