### ISSUE TITLE
Huge amount of network data

### ISSUE THREAD

**Issue by Malex21** [przemykomo/simple-planes#142] opened 2022-10-10 13:46 UTC
Hello !
While in a plane on my server, the game sends a huuuuuge amount of data per second for minecraft (about 8mbit/s, and thats my maximum network speed)
That, and the planes are very very laggy. Not only do they rubberband a lot, sometimes makes me crash (Even with connectivity mod - Which is absolutly needed to play with planes), they can sometimes take as much as 30 seconds to react to my keyboard commands (Large plane, it's more reactive for planes and helicopters)
And yes, sometimes the crashes say 'DecoderException'
This is on 1.19.2

**Comment by przemykomo** [comment] 2022-10-23 08:29
Duplicate of #119

**Closed by przemykomo** 2022-10-23 08:29 UTC
